package io.github.xingray.compose.nexus.controls

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.Dp
import io.github.xingray.compose.nexus.theme.ComponentSize

typealias SelectV2State<T> = SelectState<T>

@Composable
fun <T> rememberSelectV2State(
    initialSelected: T? = null,
    initialSelectedValues: List<T> = emptyList(),
): SelectV2State<T> = rememberSelectState(
    initialSelected = initialSelected,
    initialSelectedValues = initialSelectedValues,
)

@Composable
fun <T> NexusSelectV2(
    state: SelectV2State<T>,
    options: List<SelectOption<T>>,
    onSelect: (T) -> Unit,
    modifier: Modifier = Modifier,
    size: ComponentSize = ComponentSize.Default,
    placeholder: String = "Please select",
    disabled: Boolean = false,
    clearable: Boolean = false,
    clearIcon: (@Composable () -> Unit)? = null,
    multiple: Boolean = false,
    multipleLimit: Int = 0,
    collapseTags: Boolean = false,
    collapseTagsTooltip: Boolean = false,
    maxCollapseTags: Int = 1,
    filterable: Boolean = false,
    filterMethod: ((String, SelectOption<T>) -> Boolean)? = null,
    remote: Boolean = false,
    remoteMethod: ((String) -> List<SelectOption<T>>)? = null,
    allowCreate: Boolean = false,
    defaultFirstOption: Boolean = false,
    reserveKeyword: Boolean = true,
    loading: Boolean = false,
    loadingText: String = "Loading",
    noMatchText: String = "No matching data",
    noDataText: String = "No data",
    props: SelectOptionProps = SelectOptionProps(),
    valueKey: ((T) -> Any?)? = null,
    height: Int = 274,
    itemHeight: Int = 34,
    fitInputWidth: Boolean = true,
    dropdownWidth: Dp? = null,
    emptyValues: Set<Any?> = setOf(null),
    valueOnClear: T? = null,
    header: (@Composable () -> Unit)? = null,
    footer: (@Composable () -> Unit)? = null,
    prefix: (@Composable () -> Unit)? = null,
    empty: (@Composable () -> Unit)? = null,
    loadingContent: (@Composable () -> Unit)? = null,
    optionContent: (@Composable (SelectOption<T>, Boolean) -> Unit)? = null,
    tagContent: (@Composable (SelectOption<T>, Boolean, () -> Unit) -> Unit)? = null,
    labelContent: (@Composable (index: Int, label: String, value: T) -> Unit)? = null,
    createOption: ((String) -> SelectOption<T>)? = null,
    onChange: ((Any?) -> Unit)? = null,
    onVisibleChange: ((Boolean) -> Unit)? = null,
    onRemoveTag: ((T) -> Unit)? = null,
    onClear: (() -> Unit)? = null,
    onFocus: (() -> Unit)? = null,
    onBlur: (() -> Unit)? = null,
) {
    NexusSelect(
        state = state,
        options = options,
        onSelect = onSelect,
        modifier = modifier,
        size = size,
        placeholder = placeholder,
        disabled = disabled,
        clearable = clearable,
        clearIcon = clearIcon,
        multiple = multiple,
        multipleLimit = multipleLimit,
        collapseTags = collapseTags,
        collapseTagsTooltip = collapseTagsTooltip,
        maxCollapseTags = maxCollapseTags,
        filterable = filterable,
        filterMethod = filterMethod,
        remote = remote,
        remoteMethod = remoteMethod,
        allowCreate = allowCreate,
        defaultFirstOption = defaultFirstOption,
        reserveKeyword = reserveKeyword,
        loading = loading,
        loadingText = loadingText,
        noMatchText = noMatchText,
        noDataText = noDataText,
        props = props,
        valueKey = valueKey,
        height = height,
        itemHeight = itemHeight,
        fitInputWidth = fitInputWidth,
        dropdownWidth = dropdownWidth,
        virtualized = true,
        emptyValues = emptyValues,
        valueOnClear = valueOnClear,
        header = header,
        footer = footer,
        prefix = prefix,
        empty = empty,
        loadingContent = loadingContent,
        optionContent = optionContent,
        tagContent = tagContent,
        labelContent = labelContent,
        createOption = createOption,
        onChange = onChange,
        onVisibleChange = onVisibleChange,
        onRemoveTag = onRemoveTag,
        onClear = onClear,
        onFocus = onFocus,
        onBlur = onBlur,
    )
}
